# permissions for end users to view renovates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: renovate-viewer-role
rules:
- apiGroups:
  - renovate.renovatebot.com
  resources:
  - renovates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - renovate.renovatebot.com
  resources:
  - renovates/status
  verbs:
  - get
