# permissions for end users to edit renovates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: renovate-editor-role
rules:
- apiGroups:
  - renovate.renovatebot.com
  resources:
  - renovates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - renovate.renovatebot.com
  resources:
  - renovates/status
  verbs:
  - get
