
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - renovate.renovatebot.com
  resources:
  - renovates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - renovate.renovatebot.com
  resources:
  - renovates/finalizers
  verbs:
  - update
- apiGroups:
  - renovate.renovatebot.com
  resources:
  - renovates/status
  verbs:
  - get
  - patch
  - update
