apiVersion: renovate.renovatebot.com/v1alpha1
kind: Renovate
metadata:
  name: renovate-sample
spec:
#  version: 27.7.0
  platform:
    type: github
    endpoint: 'https://github.com/api/v3'
    token:
      secretKeyRef:
        name: 'my-secret'
        key: 'githubtoken'
#  githubToken:
#    secretKeyRef:
#      name: 'my-secret'
#      key: 'githubtoken'
  schedule: "*/10 * * * *"
  dryRun: true
  logging:
    level: info
