//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 Sebastian Poxhofer.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingSettings) DeepCopyInto(out *LoggingSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingSettings.
func (in *LoggingSettings) DeepCopy() *LoggingSettings {
	if in == nil {
		return nil
	}
	out := new(LoggingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Platform) DeepCopyInto(out *Platform) {
	*out = *in
	in.Token.DeepCopyInto(&out.Token)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Platform.
func (in *Platform) DeepCopy() *Platform {
	if in == nil {
		return nil
	}
	out := new(Platform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Renovate) DeepCopyInto(out *Renovate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Renovate.
func (in *Renovate) DeepCopy() *Renovate {
	if in == nil {
		return nil
	}
	out := new(Renovate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Renovate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenovateAppConfig) DeepCopyInto(out *RenovateAppConfig) {
	*out = *in
	in.Platform.DeepCopyInto(&out.Platform)
	out.Logging = in.Logging
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.OnBoarding != nil {
		in, out := &in.OnBoarding, &out.OnBoarding
		*out = new(bool)
		**out = **in
	}
	if in.AddLabels != nil {
		in, out := &in.AddLabels, &out.AddLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.GithubTokenSelector.DeepCopyInto(&out.GithubTokenSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenovateAppConfig.
func (in *RenovateAppConfig) DeepCopy() *RenovateAppConfig {
	if in == nil {
		return nil
	}
	out := new(RenovateAppConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenovateConfig) DeepCopyInto(out *RenovateConfig) {
	*out = *in
	if in.AddLabels != nil {
		in, out := &in.AddLabels, &out.AddLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenovateConfig.
func (in *RenovateConfig) DeepCopy() *RenovateConfig {
	if in == nil {
		return nil
	}
	out := new(RenovateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenovateList) DeepCopyInto(out *RenovateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Renovate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenovateList.
func (in *RenovateList) DeepCopy() *RenovateList {
	if in == nil {
		return nil
	}
	out := new(RenovateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RenovateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenovateSpec) DeepCopyInto(out *RenovateSpec) {
	*out = *in
	in.RenovateAppConfig.DeepCopyInto(&out.RenovateAppConfig)
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
	out.Logging = in.Logging
	out.SharedCache = in.SharedCache
	out.ScalingSpec = in.ScalingSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenovateSpec.
func (in *RenovateSpec) DeepCopy() *RenovateSpec {
	if in == nil {
		return nil
	}
	out := new(RenovateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenovateStatus) DeepCopyInto(out *RenovateStatus) {
	*out = *in
	if in.DiscoveredRepositories != nil {
		in, out := &in.DiscoveredRepositories, &out.DiscoveredRepositories
		*out = make([]RepositoryPath, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenovateStatus.
func (in *RenovateStatus) DeepCopy() *RenovateStatus {
	if in == nil {
		return nil
	}
	out := new(RenovateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingSpec) DeepCopyInto(out *ScalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingSpec.
func (in *ScalingSpec) DeepCopy() *ScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedCache) DeepCopyInto(out *SharedCache) {
	*out = *in
	out.RedisConfig = in.RedisConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedCache.
func (in *SharedCache) DeepCopy() *SharedCache {
	if in == nil {
		return nil
	}
	out := new(SharedCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedCacheRedisConfig) DeepCopyInto(out *SharedCacheRedisConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedCacheRedisConfig.
func (in *SharedCacheRedisConfig) DeepCopy() *SharedCacheRedisConfig {
	if in == nil {
		return nil
	}
	out := new(SharedCacheRedisConfig)
	in.DeepCopyInto(out)
	return out
}
